### ISSUE TITLE
Error in docker.yml file for mysql:db 'platform'

### ISSUE THREAD

**Issue by hzahera** [dice-group/LabENT#18]
When I run docker-compose file on unbuntu machine, it shows an error 
`Unsupported config option for services.db: 'platform'` for mysql platform. 

```
  db:
    image: 'mysql:5.7'
    platform: linux/amd64
    volumes:
```

This error has be resolved, when I removed the platform option: 

```
  db:
    image: 'mysql:5.7'
    volumes:
```
